export const API_URL = "https://64464e200431e885f00e57f0.mockapi.io/cars";
export const MILISECONDS_IN_SECOND = 1000;
export const MILISECONDS_IN_MINUTE = MILISECONDS_IN_SECOND * 60;
export const MILISECONDS_IN_HOUR = MILISECONDS_IN_MINUTE * 60;
export const MILISECONDS_IN_DAY = MILISECONDS_IN_HOUR * 24;
export const MILISECONDS_IN_MONTH = MILISECONDS_IN_DAY * 30;
export const MILISECONDS_IN_YEAR = MILISECONDS_IN_MONTH * 12;
